pipeline:
  agent:
    any:
    triggers:
      GenericTrigger:
        causeString: "Triggered from Webhook"
        token: "unique-token-to-start-the-current-pipeline"

  stages:
    - stage: "checkout"
      steps:
        - sh 'checkout([$class: "GitSCM", branches: [[name: "*/master"]], extensions: [], userRemoteConfigs: [[url: "https://github.com/prayas2409/jenkinsPipelineYaml.git" ]]])'
    - stage: "terraform Init"
      steps:
        - sh 'terraform init > tfflogs.txt 2>&1 &'
    - stage: "tf plan"
      steps:
        - sh 'terraform plan'
