pipeline:
  agent:
    any:
  stages:
    - stage: "clone" 
      steps: sh 'git clone https://github.com/prayas2409/jenkinsPipelineYaml.git'

    - stage: "terraform Init"
      steps:
        - sh 'cd jenkinsPipelineYaml && terraform init'
    - stage: "tf plan"
      steps:
        - sh 'terraform plan'
