pipeline:
  agent:
    none:
    triggers:
      GenericTrigger:
        causeString: "Triggered from Webhook"
        token: "unique-token-to-start-the-current-pipeline"

  stages:
    - stage: "Stage1"
      steps:
        - echo "1"
    - stage: "Stage2"
      steps:
        - echo "2"
