pipeline:
  agent:
    any:
  stages:
    - stage: "clone" 
      steps: sh 'if [[ ! -f jenkinsPipelineYaml ]]; then git clone https://github.com/prayas2409/jenkinsPipelineYaml.git fi'

    - stage: "terraform Init"
      steps:
        - sh 'cd jenkinsPipelineYaml && terraform init'
    - stage: "tf plan"
      steps:
        - sh 'cd jenkinsPipelineYaml && terraform plan'
    - stage: "deploy"
      steps:
        - sh 'cd jenkinsPipelineYaml && terraform apply'
